# https://docs.github.com/en/actions
name: hallo-lambda-ci
on:
  push:
    branches: [ "deploy_py_*" ]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
#        with:
#          ref: 'master'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip' # caching pip dependencies
      - name: Building and Packaging sources
        run: |
          chmod +x env_init.sh
          ./env_init.sh
      - name: Deploying Lambda to AWS
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: lambdo-bot
          zip_file: py_lambda_package.zip
          timeout: 10
          handler: lambda_handler
          role: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GH_ACTIONS_bath_house_bot_role
          runtime: python3.8
          memory_size: 128
