# https://docs.github.com/en/actions
name: hallo-lambda-ci
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu:21.10
    steps:
      - uses: actions/checkout@v3
#        with:
#          ref: 'master'
      # https://github.com/marketplace/actions/aws-lambda-python-deploy
      - name: git_config_workaround
        run: sudo /usr/bin/git config --system --add safe.directory /github/workspace
      - name: Deploy code to Lambda
        uses: denzalman/lambda-python-action@v1.1.0
        with:
          lambda_layer_arn: 'arn:aws:lambda:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:layer:telegram-layer'
          lambda_function_name: 'lambdo-bot'
          lambda_region: ${{ secrets.AWS_REGION }}
          requirements_txt: 'requirements.txt'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
